const $=id=>document.getElementById(id), money=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v||0), n=id=>Number($(id).value)||0;let C={};
function buckets(req){let s=[5,10,15,20],p=[n('p5'),n('p10'),n('p15'),n('p20')],best=null;for(let a=0;a<=12;a++)for(let b=0;b<=12;b++)for(let c=0;c<=12;c++)for(let d=0;d<=12;d++){let x=[a,b,c,d],L=a*5+b*10+c*15+d*20;if(L<req||!L)continue;let cost=x.reduce((z,v,i)=>z+v*p[i],0);if(!best||cost<best.cost||(cost===best.cost&&L<best.L))best={L,cost,parts:x.map((v,i)=>v?v+'×'+s[i]+' L':'').filter(Boolean).join(' + ')} }return best||{L:0,cost:0,parts:'Sem combinação'} }
function calc(){let w=n('w'),l=n('l'),h=n('h'),walls=2*(w+l)*h,ceil=$('ceiling').checked?w*l:0,area=Math.max(0,walls+ceil-n('doors')*2-n('windows')*1.5+n('extra')),coats=n('coats'),liters=area*coats/Math.max(.1,n('coverage'))*(1+n('waste')/100),b=buckets(liters),labor=area*n('labor'),paint=liters*n('paint'),primer=area*n('primer'),filler=area*n('filler'),materials=paint+primer+filler+b.cost,sub=Math.max(0,labor+materials+n('travel')-n('discount')),vat=sub*n('vat'),total=sub+vat;Object.assign(C,{area,liters,b,labor,paint,primer,filler,materials,sub,vat,total,coats});$('walls').textContent=walls.toFixed(1)+' m²';$('ceil').textContent=ceil.toFixed(1)+' m²';$('area').textContent=area.toFixed(1)+' m²';$('liters').textContent=liters.toFixed(1)+' L';$('bucket').innerHTML='<b>'+b.parts+'</b><br>Total: '+b.L+' L · Sobra: '+Math.max(0,b.L-liters).toFixed(1)+' L<br>Custo: '+money(b.cost);$('laborTotal').textContent=money(labor);$('materials').textContent=money(materials);$('subtotal').textContent=money(sub);$('grand').textContent=money(total);$('total').textContent=money(total)}
document.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calc));$('ceiling').onchange=calc;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='quote')preview();if(b.dataset.tab==='history')history()});
$('toQuote').onclick=()=>{preview();document.querySelector('[data-tab=quote]').click()};
function preview(){calc();let client=$('client').value||'Cliente';$('preview').innerHTML='<h2>'+($('company').value||'Pintor PRO Portugal')+'</h2><p><b>Cliente:</b> '+client+'<br><b>Serviço:</b> '+($('job').value||'Pintura')+'<br><b>Área:</b> '+C.area.toFixed(1)+' m²<br><b>Tinta:</b> '+C.liters.toFixed(1)+' L<br><b>Baldes:</b> '+C.b.parts+'</p><hr><p>Mão de obra: '+money(C.labor)+'<br>Materiais: '+money(C.materials)+'<br>Deslocação: '+money(n('travel'))+'<br>Desconto: -'+money(n('discount'))+'<br>IVA: '+money(C.vat)+'</p><h2>TOTAL: '+money(C.total)+'</h2>'}
function data(){calc();return {id:Date.now(),date:new Date().toLocaleDateString('pt-PT'),client:$('client').value||'Cliente',phone:$('phone').value,address:$('address').value,job:$('job').value||'Pintura',area:C.area,liters:C.liters,buckets:C.b.parts,total:C.total}}
$('save').onclick=()=>{let a=JSON.parse(localStorage.pintorHistory||'[]');a.unshift(data());localStorage.pintorHistory=JSON.stringify(a.slice(0,100));alert('Orçamento guardado.');history()};
function history(){let a=JSON.parse(localStorage.pintorHistory||'[]');$('list').innerHTML=a.length?a.map(x=>`<div class="history"><b>ORC-${String(x.id).slice(-5)} · ${x.client}</b><br><small>${x.date} · ${x.area.toFixed(1)} m² · ${money(x.total)}</small><br><button onclick="loadQ(${x.id})">Abrir</button><button onclick="delQ(${x.id})">Apagar</button></div>`).join(''):'<p class="muted">Sem orçamentos guardados.</p>'}
window.loadQ=id=>{let x=JSON.parse(localStorage.pintorHistory||'[]').find(y=>y.id===id);if(x){$('client').value=x.client;$('phone').value=x.phone||'';$('address').value=x.address||'';$('job').value=x.job||'';document.querySelector('[data-tab=quote]').click();preview()}};window.delQ=id=>{localStorage.pintorHistory=JSON.stringify(JSON.parse(localStorage.pintorHistory||'[]').filter(x=>x.id!==id));history()};
$('clear').onclick=()=>{if(confirm('Apagar todos os orçamentos?')){localStorage.removeItem('pintorHistory');history()}};
$('share').onclick=()=>{let d=data(),t=`PINTOR PRO PORTUGAL\nCliente: ${d.client}\nÁrea: ${d.area.toFixed(1)} m²\nTinta: ${d.liters.toFixed(1)} L\nBaldes: ${d.buckets}\nTOTAL: ${money(d.total)}`;navigator.share?navigator.share({title:'Orçamento de pintura',text:t}):navigator.clipboard.writeText(t).then(()=>alert('Resumo copiado.'))};
$('pdf').onclick=()=>window.print();$('settingsSave').onclick=()=>{localStorage.pintorSettings=JSON.stringify({company:$('company').value,nif:$('nif').value,phone:$('companyPhone').value,email:$('email').value,address:$('companyAddress').value});alert('Definições guardadas.')};
$('reset').onclick=()=>location.reload();
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');calc();
